### ISSUE TITLE
Javascript Error / Adminpage will not be displayed

### ISSUE THREAD

**Issue by aehm2k5** [ClicShopping/ClicShopping_V3#30] opened 2023-07-24 11:14 UTC
**Describe the bug**

**To Reproduce**
just did a fresh install of the latest version, imported demodata, nothing else changed,
wanted to goto Admin Dasboard logged in and get a rotating circle.
watched Browser-Console and saw a Error:

error with chrome:
[PWA Builder] active service worker found, no need to register
footer.js:16 Uncaught ReferenceError: Tooltip is not defined
    at footer.js:16:66
    at Array.map (<anonymous>)
    at footer.js:16:40

error with edge:
Uncaught TypeError: Cannot read properties of null (reading 'scrollHeight')
    at rc2Contentscript.js:249:91

**Expected behavior**
login dashboard should be visible 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome / Edge / Firefox
 - Version latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ClicShopping** [comment] 2023-07-24 13:24
Hello,
Thank you for your report
I can not see or reproduce this error, I need more information, screenshot, version you use:
Could you add screenshot,please,
Coud you open the console and see the error

In my case, I see my dashboard with 4 graphics.

Also to help you, you can go in includes/config_clicshopping.php and change the elements by this approach :
```
  define('MODE_B2B_B2C', 'True'); // true ou false
  define('MODE_DEMO' , 'False'); // only demo mode
  define('DEBUG_MODE', 'True'); // only for development
```

Let me know.
Thank you

**Comment by aehm2k5** [comment] 2023-07-24 15:22
as i tried with a fresh firefox installation, so no use of plugins,
now getting server error's after changing define('DEBUG_MODE', 'True'); // only for development

[Mon Jul 24 17:18:28.601745 2023] [proxy_fcgi:error] [pid 1657602:tid 139663067047680] (70007)The timeout specified has expired: [client xx.xxx.xxx.xxx:0] AH01075: Error dispatchi
ng request to : (polling), referer: https://xxx.xxxxxx.xx/install/install.php?step=4
[Mon Jul 24 17:20:32.932118 2023] [proxy_fcgi:error] [pid 1657602:tid 139663192872704] (70007)The timeout specified has expired: [client xx.xxx.xxx.xxx:0] AH01075: Error dispatching request to : (polling)


just made a new fresh install...

**Comment by aehm2k5** [comment] 2023-07-24 15:50
Must be something with the dbname or username both ends with: "-shop"

**Comment by ClicShopping** [comment] 2023-07-24 16:16
it's weird because the install has nothing to do with config_clicshopping.php

about login : https://ipinfo.io works fine and you can see on the demo website login but for the futur I will insert a check.

```
/*
 if (Is::IpAddress($ip) && (!empty($ip) || !\is_null($ip))) {
    $details = file_get_contents("https://ipinfo.io/{$ip}/geo");

    if ($details !== false) {
      $details = json_decode($details);
      if(isset($details->country)) {
        $country = $details->country;
        echo "<script>$('svg path[data-country-code={$country}]').attr('fill', '#197ac6').attr('fill-opacity', '0.15');</script>";
      }
    }
  }
*/
```
About sizeDb() please remove this line in includes/Modules/hooks/ClicShoppingAdmin\Dashboard\ActionInformation.php
`' . DB::sizeDb() . ' `

Ler me know

**Comment by aehm2k5** [comment] 2023-07-24 16:19
now are the arrows here

**Comment by ClicShopping** [comment] 2023-07-24 16:19
[24-Jul-2023 17:23:36 Europe/Berlin] PHP Warning: file_get_contents(https://ipinfo.io/xx.xxx.xxx.xxx/geo): Failed to open stream: HTTP request failed! HTTP/1.1 503 Service Unavailable

**Comment by ClicShopping** [comment] 2023-07-24 16:25
if everything for that works fine, please close the issue

**Closed** 2023-07-24 16:26 UTC
